<?xml version="1.0" encoding="utf-8"?><Database Name="Expensite" Class="ExpensiteDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=RADHU-PC\SQLEXPRESS2008;Initial Catalog=Expensite;Integrated Security=True" SettingsObjectName="Expensite.Data.Properties.Settings" SettingsPropertyName="ExpensiteConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Expense" Member="Expenses">
    <Type Name="Expense">
      <Column Name="ExpenseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiptId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpenseDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Expense_Ref" Member="Refs" ThisKey="ExpenseId" OtherKey="ExpenseId" Type="Ref" />
      <Association Name="Receipt_Expense" Member="Receipt" ThisKey="ReceiptId" OtherKey="ReceiptId" Type="Receipt" IsForeignKey="true" />
      <Association Name="User_Expense" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ExpenseType" Member="ExpenseTypes">
    <Type Name="ExpenseType">
      <Column Name="ExpenseTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExpenseTypeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.R" Member="Rs">
    <Type Name="R">
      <Column Name="ReceiptID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiptPath" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_R" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Receipt" Member="Receipts">
    <Type Name="Receipt">
      <Column Name="ReceiptId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExpenseTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CurrencyTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ReceiptPath" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="Comment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Receipt_Expense" Member="Expenses" ThisKey="ReceiptId" OtherKey="ReceiptId" Type="Expense" />
      <Association Name="Receipt_Reference" Member="References" ThisKey="ReceiptId" OtherKey="ReceiptId" Type="Reference" />
    </Type>
  </Table>
  <Table Name="dbo.Ref" Member="Refs">
    <Type Name="Ref">
      <Column Name="RefId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExpenseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReportId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Expense_Ref" Member="Expense" ThisKey="ExpenseId" OtherKey="ExpenseId" Type="Expense" IsForeignKey="true" />
      <Association Name="Report_Ref" Member="Report" ThisKey="ReportId" OtherKey="ReportId" Type="Report" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reference" Member="References">
    <Type Name="Reference">
      <Column Name="RefId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReceiptId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExpenseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Receipt_Reference" Member="Receipt" ThisKey="ReceiptId" OtherKey="ReceiptId" Type="Receipt" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Report" Member="Reports">
    <Type Name="Report">
      <Column Name="ReportId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Amount" Type="System.Single" DbType="Real" CanBeNull="true" />
      <Column Name="ReportName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Owner" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Report_Ref" Member="Refs" ThisKey="ReportId" OtherKey="ReportId" Type="Ref" />
      <Association Name="User_Report" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserDetail" Member="UserDetails">
    <Type Name="UserDetail">
      <Column Name="UserDetailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="FName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="LName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UserType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MobileNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Appartment" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Street" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pincode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_UserDetail" Member="User" ThisKey="UserId" OtherKey="UserId" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EMail" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="UpdatedDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_Expense" Member="Expenses" ThisKey="UserId" OtherKey="UserId" Type="Expense" />
      <Association Name="User_R" Member="Rs" ThisKey="UserId" OtherKey="UserId" Type="R" />
      <Association Name="User_Report" Member="Reports" ThisKey="UserId" OtherKey="UserId" Type="Report" />
      <Association Name="User_UserDetail" Member="UserDetails" ThisKey="UserId" OtherKey="UserId" Type="UserDetail" />
    </Type>
  </Table>
  <Table Name="dbo.CurrencyType" Member="CurrencyTypes">
    <Type Name="CurrencyType">
      <Column Name="CurrencyTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CurrencyTypeName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CurrencySymbol" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </Type>
  </Table>
</Database>